on: [ push, pull_request ]

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: JJ/raku-test-action@v2
      - name: Debug
        run: |
          ls
          raku -v
          zef install --/test DBIish App::Prove6
      - name: Test
        run: prove6
